### PR TITLE
Fix swipe back when hiding navbar

### PR DESCRIPTION
**Pull request by RichardLindhout**

### CODE REVIEW

**Comment by RichardLindhout** [comment]
https://stackoverflow.com/a/37092015/2508481

**Comment by grahammendick** [comment]
Hey, thanks for raising this after our chat on Twitter. Just to summarise my understanding -

You're migrating from React Native Navigation and you have a custom navigation bar that you can't easily move over to the Navigation router's native `NavigationBar`. But if you set the `NavigationBar` to hidden then you lose the swipe back gesture on iOS. You've tried squeezing the content into a custom `TitleView` but that doesn't work for your full width search bar. So you want a way to hide the NavigationBar without losing the swipe back gesture.

I can't accept the PR as it is because that would change the current behaviour of the `hidden` prop on the `NavigationBar`. But what about if we use your way to hide if there's no `NavigationBar` in the Scene. So a hidden `NavigationBar` would still prevent the swipe back but no `NavigationBar` at all would keep the swipe back. Does that sound good?

Currently the Navigation router looks through the view hierarchy to find the navigation bar. This is fast at the moment because it's guaranteed to find one almost straightaway. But with the proposed change then this will be much slower because it'll have to look through  all the subviews to make sure there isn't one.

Instead of searching through all subviews we could use the `NSNotificationCenter` to build an efficient way to find the navigation bar. When the view loads the `NVSceneController` can post a message on the notification center. The `NavigationBar` can listen for this message and tell the scene that it's there. 

Let me know what you think.

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by grahammendick** [comment]
You can [track my progress](https://github.com/grahammendick/navigation/compare/no-navbar) (reached out to @RichardLindhout on Twitter to check he's happy for me to start on it)

**Comment by RichardLindhout** [comment]
Amazing @grahammendick, I really appreciate all your hard work!!

**Comment by grahammendick** [comment]
I'm [testing it out](https://github.com/grahammendick/navigation/compare/no-navbar) but there's a weird animation when swiping back between from a screen with no navigation bar to one with (and vice versa). You can see how the title appears over the top where it thinks the navigation bar should be. I guess for you it doesn't matter because you're turning off the navigation bar for all screens, right?

https://user-images.githubusercontent.com/1761227/220197990-da86f116-306c-43f3-8d51-0bf70fa7353d.mov

**Comment by RichardLindhout** [comment]
Looking forward to it!

**Comment by grahammendick** [comment]
Closing in favour of #677

**Pull request closed without merging**
