### PR TITLE
Change IconResolver to use Fresco ImagePipeline directly

### PR DESCRIPTION
**Pull request by mpiannucci**
Allows for tinting icons in BottomNavigationView menus and TabLayout tabs

### CODE REVIEW

**Comment by grahammendick** [comment]
Really great work. Thank you!

**Comment by grahammendick** [comment]
Do we need to follow this advice from the ["Using the Image Pipeline Directly"](https://frescolib.org/docs/using-image-pipeline.html) guide?

> Using the image pipeline directly is challenging because of the memory usage. Drawees automatically keep track of whether or not your images need to be in memory. They will swap them out and load them back as soon as they need to be displayed. If you are using the image pipeline directly, your app must repeat this logic.

**Comment by grahammendick** [comment]
And this advice too?

> If you do not keep a Java reference to a CloseableReference returned by the pipleine, the CloseableReference will get garbage collected and the underlying Bitmap may get recycled while still being used. If you do not close the CloseableReference once you are done with it, you risk memory leaks and OOMs.

**Comment by mpiannucci** [comment]
Yeah I take care of that in the IconResolver. Because we don’t want Fresco to manage the bitmap, we copy the bitmap so it not owned by Fresco anymore then close the reference which cleans up the original but not the copy. 

If you don’t copy the bitmap it gets collected irregularly and the icons don’t show consistently.

**Pull request merged**
