### PR TITLE
Prevented pending Fragment Transactions running when NavigationStack is detached

### LINKED ISSUE #351: java.lang.IllegalArgumentException No view found for id 0x2e7 (unknown) for fragment ScreenFragment{aba6d90 (389db4fd-87b3-4a02-8a21-096e57a6981d) id=0x2e7}
I'm moving this issue out of [Several android crashes #348](https://github.com/grahammendick/navigation/issues/348) so we can focus on it. 

Basically, I am unable to reproduce this one on the simulator but it does happen quite often on release build on the device.

```
java.lang.IllegalArgumentException No view found for id 0x2e7 (unknown) for fragment ScreenFragment{aba6d90 (389db4fd-87b3-4a02-8a21-096e57a6981d) id=0x2e7} 
    FragmentManagerImpl.java:875 androidx.fragment.app.FragmentManagerImpl.moveToState
    FragmentManagerImpl.java:2100 androidx.fragment.app.FragmentManagerImpl.addAddedFragments
    FragmentManagerImpl.java:1874 androidx.fragment.app.FragmentManagerImpl.executeOpsTogether
    FragmentManagerImpl.java:1830 androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute
    FragmentManagerImpl.java:1727 androidx.fragment.app.FragmentManagerImpl.execPendingActions
    FragmentManagerImpl.java:150 androidx.fragment.app.FragmentManagerImpl$2.run
    Handler.java:883 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:7356 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:492 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:930 com.android.internal.os.ZygoteInit.main
```

### PR DESCRIPTION
**Pull request by grahammendick**
Fixes #351 

There are two error scenarios for the [steps in issue 351](https://github.com/grahammendick/navigation/issues/351#issuecomment-602027048)

1.  The transactions are created before the `NavigationStack` is detached but only run after.
2.  The transactions are created and run after the `NavigationStack` is detached due to the `setState` running after reload

Added checks for both scenarios. Executing the pending transactions on detach takes care of 1 and preventing the navigation if not attached takes care of 2

### CODE REVIEW

**Comment by grahammendick** [comment]
@gabrielbull Could you try out this fix and let me know if it works for you, please?

**Comment by gabrielbull** [comment]
@grahammendick Yes I'll test it

**Comment by grahammendick** [comment]
Hey @gabrielbull How are you?

I reorganised the way I handled Fragments in `navigation-react-native v6.10.0`. So I had a go at recreating this bug following [steps in issue 351](https://github.com/grahammendick/navigation/issues/351#issuecomment-602027048). I couldn't recreate it! I repeated the steps probably about 50 times and no error. To double check, I went back to an older version of navigation-react-native and I got the error immediately (on first repeat). 

So I'm going to close #351 but I wanted to check in with you first.

**Comment by gabrielbull** [comment]
I just release a few days ago the version with the patch. So far, no errors have popped up. I'll make sure to test this one on the next release, but it is not due until 1 and a half months.

**Comment by grahammendick** [comment]
Thanks that sounds great. I'll close #351 but please keep me updated on the progress of the patch  version

**Pull request closed without merging**
