### PR TITLE
fix font family not being reflected for android

### LINKED ISSUE #691: Remove or Hide Flashing while Navigating [Font Family not getting reflected]
Hello, Graham, thanks for this amazing navigation library was pretty simple to setup, also how can i theme the bottom navigation bar

How can i reduce flashing while navigation. I am attaching a screen-record of the same. This is not visible in some of the apps that are built natively also on react native that i know.

https://user-images.githubusercontent.com/17390257/229299259-a9912a49-4372-4d8f-b7ef-e374a38bcc95.mp4

### PR DESCRIPTION
**Pull request by afkcodes**
Font Family was not getting updated for latest version of android, in my case Android 13. 
Thanks @grahammendick  for encouragement. 

Fixes #691

### CODE REVIEW

**Comment by grahammendick** [comment]
This is really great, thanks so much!

**Comment by grahammendick** [comment]
Thanks again, it works great in all 4 components on old and new architecture. I'll thank you in the release notes, too

**Comment by grahammendick** [comment]
I just released navigation-react-native v9.2.1 and [thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.2.1-NavigationReactNative)

**Comment by afkcodes** [comment]
Thanks @grahammendick  @RichardLindhout

**Pull request merged**
